version : '3.8'
services :configs:
  php-apache-environment:
  image: nafhi/php
  container_name: php-apache
  depends_on: 
  - db
  volumes:
  - ./php/src:/var/www/html/
  ports:
  - 8000:80
  networks :
  - backend

db:
  container_name: db
  image: mysql
  restart: always
  environment:
    MYSQL_ROOT_PASSWORD: admin
    MYSQL_DATABASE: php_user
  ports:
  - "3306:3306"
  volumes:
  - db:/var/lib/mysql
  - ./php_user.sql:/docker-entrypoint-initdb.d/php_user.sql
  networks:
  - backend

volumes:
  db:

networks:
  backend:
    name: backend-network

    
